modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"
license = "Custom"

[[mods]]
modId = "vinery"
version = "${version}"
displayName = "[Let's Do] Vinery"
authors = "Jason13Official, Satisfy"
credits = "Cristelknight, BaumeisterJO, cph101dev, MissLilitu, CR-055"
description = '''
In Vino Veritas - it's time for wine! Build your own vineyard, produce wine, and establish your own winery.
'''
logoFile = "pack.png"

[[dependencies.vinery]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vinery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vinery]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[incompatibleMods]]
modId = "copperative"