name: Publish
on:
  workflow_dispatch:
    inputs:
      release_as_beta:
        description: "Mark as pre-release"
        required: true
        type: boolean
        default: true
permissions:
  contents: write
  packages: write


jobs:
  mod-build:
    name: 📦 Build mod
    runs-on: macos-14
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1 # This is effectively git clone
      - name: setup JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 21
          distribution: 'temurin' # Installs java
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew # Execution workaround for unix-based systems
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3 # Speeds up build time by about 5 mins :P
      - name: Execute Gradle build
        run: ./gradlew build --warning-mode all # Builds the mod into a jar file
      - uses: actions/upload-artifact@v4.3.0
        with:
          name: build-common
          path: build/libs/
      - uses: actions/upload-artifact@v4.3.0
        with:
          name: build-fabric
          path: fabric/build/libs/
      - uses: actions/upload-artifact@v4.3.0
        with:
          name: build-forge
          path: forge/build/libs/

          mod_version: ${{ steps.read_properties.outputs.mod_version }}

